### ISSUE TITLE
“No such file or directory” error on Android 13

### ISSUE THREAD

**Issue by HongheZ** [honeynet/droidbot#145]
Hello, wehen I used DroidBot on Android 13 devices, it shows this error:

`INFO:Device:waiting for device
ls: /data/local/tmp/minicap-devel: No such file or directory
ls: 2>/dev/null: No such file or directory
WARNING:Device:push_file file does not exist: d:\pycharm\project\droidbot\droidbot-master\droidbot\resources\minicap\jni\libs\android-33
\arm64-v8a\minicap.so
Traceback (most recent call last):
  File "d:\pycharm\project\droidbot\droidbot-master\droidbot\droidbot.py", line 139, in start
    self.device.set_up()
  File "d:\pycharm\project\droidbot\droidbot-master\droidbot\device.py", line 143, in set_up
    adapter.set_up()
  File "d:\pycharm\project\droidbot\droidbot-master\droidbot\adapter\minicap.py", line 83, in set_up
    device.push_file(local_file=minicap_so_path, remote_dir=self.remote_minicap_path)
  File "d:\pycharm\project\droidbot\droidbot-master\droidbot\device.py", line 756, in push_file
    self.adb.run_cmd(["push", local_file, remote_dir])
  File "d:\pycharm\project\droidbot\droidbot-master\droidbot\adapter\adb.py", line 68, in run_cmd
    r = subprocess.check_output(args).strip()
  File "D:\Python\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Python\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
`

Would you please tell me how to solve this error? Thank you!

**Comment by pubeier** [comment]
目前droidbot还不支持Android13，需要更低的android版本！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "honeynet/droidbot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 上午9:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[honeynet/droidbot] “No such file or directory” error on Android 13 (Issue #145)





 
Hello, wehen I used DroidBot on Android 13 devices, it shows this error:
 
INFO:Device:waiting for device ls: /data/local/tmp/minicap-devel: No such file or directory ls: 2&gt;/dev/null: No such file or directory WARNING:Device:push_file file does not exist: d:\pycharm\project\droidbot\droidbot-master\droidbot\resources\minicap\jni\libs\android-33 \arm64-v8a\minicap.so Traceback (most recent call last): File "d:\pycharm\project\droidbot\droidbot-master\droidbot\droidbot.py", line 139, in start self.device.set_up() File "d:\pycharm\project\droidbot\droidbot-master\droidbot\device.py", line 143, in set_up adapter.set_up() File "d:\pycharm\project\droidbot\droidbot-master\droidbot\adapter\minicap.py", line 83, in set_up device.push_file(local_file=minicap_so_path, remote_dir=self.remote_minicap_path) File "d:\pycharm\project\droidbot\droidbot-master\droidbot\device.py", line 756, in push_file self.adb.run_cmd(["push", local_file, remote_dir]) File "d:\pycharm\project\droidbot\droidbot-master\droidbot\adapter\adb.py", line 68, in run_cmd r = subprocess.check_output(args).strip() File "D:\Python\lib\subprocess.py", line 411, in check_output return run(*popenargs, stdout=PIPE, timeout=timeout, check=True, File "D:\Python\lib\subprocess.py", line 512, in run raise CalledProcessError(retcode, process.args, 
 
Would you please tell me how to solve this error? Thank you!

**Comment by HongheZ** [comment]
Hello, thank you for your answer! Are there any future updates planned to make Droidbot support Android 13? I know that Doridbot now supports Android 12.

您好，谢谢您的回答!未来Droidbot是否会有支持Android 13的更新计划?我知道Doridbot现在已经支持Android 12了。
