### ISSUE TITLE
ModuleNotFoundError: No module named 'start'

### ISSUE THREAD

**Issue by liuyiyuan8888** [honeynet/droidbot#157]
I have success install droidbot use: pip3 install -e .  in WIN10  as:
successfully built droidbot
WARNING: Ignoring invalid distribution -ip (d:\programfiles\python39\lib\site-packages)
Installing collected packages: droidbot
Successfully installed droidbot-1.0.2b4

but run " droidbot -h"  failed:
E:\AITestTT\droidbot>droidbot -h
Traceback (most recent call last):
  File "D:\ProgramFiles\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramFiles\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramFiles\Python39\Scripts\droidbot.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'start'

**Comment by IdioGuarino** [comment]
Hi, I'm facing the same problem. This is my error message:

```
Traceback (most recent call last):
  File "<myhomedir>/myenv310/bin/droidbot", line 33, in <module>
    sys.exit(load_entry_point('droidbot==1.0.2b4', 'console_scripts', 'droidbot')())
  File "<myhomedir>/myenv310/bin/droidbot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'start'
```

**Comment by Gitsvn2016** [comment]
how to fix it?
