### ISSUE TITLE
 ImportError: No module named _markerlib

### ISSUE THREAD

**Issue by pavankumar9** [honeynet/droidbot#23]
I am getting below error. Can u please help me in resolving these issues:

pavans-MacBook-Pro:mobile_auto pavan$ pip install -e droidbot
Obtaining file:///Users/pavan/mydata/office/mobile_auto/droidbot
Collecting androguard (from droidbot==1.0.0a2)
  Downloading androguard-3.0.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 180kB/s 
Collecting pillow (from droidbot==1.0.0a2)
  Downloading Pillow-3.3.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.2MB)
    100% |████████████████████████████████| 3.2MB 234kB/s 
Collecting distribute (from androguard->droidbot==1.0.0a2)
  Downloading distribute-0.7.3.zip (145kB)
    100% |████████████████████████████████| 153kB 931kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/distribute.egg-info
    writing requirements to pip-egg-info/distribute.egg-info/requires.txt
    writing pip-egg-info/distribute.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/distribute.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/distribute.egg-info/dependency_links.txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hk/wbq0s2sn1sl87ycbpvt3v3580000gn/T/pip-build-l7Px9C/distribute/setup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "setuptools/command/egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "pkg_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "pkg_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "pkg_resources.py", line 2471, in requires
        dm = self._dep_map
      File "pkg_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "pkg_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named _markerlib

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hk/wbq0s2sn1sl87ycbpvt3v3580000gn/T/pip-build-l7Px9C/distribute/

**Comment by ylimit** [comment]
Hello, 
droidbot doesn't require markerlib, so maybe there was something wrong with your setuptools.
Maybe you could try `pip install -U setuptools`.

**Comment by pavankumar9** [comment]
Tried no luck.. Still facing the same issue:

pavans-MacBook-Pro:mobile_auto pavan$ pip install -U setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/site-packages

**Comment by LuD1161** [comment]
I faced the same issue , use this :

easy_install distribute

(http://stackoverflow.com/questions/35780537/error-no-module-named-markerlib-when-installing-some-packages-on-virtualenv)

Now it's working :)
