### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by SamAchten** [honeynet/droidbot#30]
When trying to install Droidbot I get the following error.
Is this a known bug, am I doing something wrong or am I just plain stupid? :)

Thanks in advance,
Sam

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/pillow/setup.py", line 753, in <module>

    zip_safe=not debug_build(), )

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run

    self.build_extensions()

  File "/tmp/pip_build_root/pillow/setup.py", line 521, in build_extensions

    ' using --disable-%s, aborting' % (f, f))

ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-AQtfcn-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pillow

**Comment by ylimit** [comment]
Hi, I haven't seen this before.
It seems like you should install `zlib` and `pillow` manually. Please refer to:
http://stackoverflow.com/questions/36563613/python-pillow-not-installing-under-osx

**Comment by SamAchten** [comment]
Thank you for the fast response. I ran the following commands, and now its working!
sudo apt-get install zlib1g-dev
sudo apt-get install libjpeg8-dev
sudo apt-get install python-dev
pip install pillow
pip install -e droidbot

Thanks again!
