### ISSUE TITLE
droidbot.adapter.adb.ADBException

### ISSUE THREAD

**Issue by breezedong** [honeynet/droidbot#32]
Hello,ylimit
I have install droidbot in my windows PC and  all prerequisite are installed.

connect nexus 5 to my PC via adb as follow:
```
E:\PaperWorkplace\droidbot>adb devices
List of devices attached
03075e3f08d4cc52        device
``` 
Then I run the droidbot and got problem as follow:
`E:\PaperWorkplace\droidbot>droidbot -d 03075e3f08d4cc52 -a dae5b93d99fe9d6d80d647a8a6dbbaf1.apk -env none -event utg_dynamic

INFO:Device:waiting for device
Traceback (most recent call last):
  File "D:\Program Files\Python2.7\Scripts\droidbot-script.py", line 9, in <module>
    load_entry_point('droidbot', 'console_scripts', 'droidbot')()
  File "e:\paperworkplace\droidbot\droidbot\droidbot\start.py", line 76, in main
    quiet=opts.quiet)
  File "e:\paperworkplace\droidbot\droidbot\droidbot\droidbot.py", line 49, in __init__
    self.device = Device(device_serial, output_dir=self.output_dir)
  File "e:\paperworkplace\droidbot\droidbot\droidbot\device.py", line 60, in __init__
    self.connect()
  File "e:\paperworkplace\droidbot\droidbot\droidbot\device.py", line 148, in connect
    self.get_adb()
  File "e:\paperworkplace\droidbot\droidbot\droidbot\device.py", line 198, in get_adb
    self.adb = ADB(self)
  File "e:\paperworkplace\droidbot\droidbot\droidbot\adapter\adb.py", line 54, in __init__
    raise ADBException()
droidbot.adapter.adb.ADBException`

I cannot find the answer.

**Comment by yzygitzh** [comment]
Hi breezedong,

Seems that DroidBot thought there was no online device, that is, the 
`adb devices`
command returns no usable device. I suggest trying to insert some print or check statements around line 54 of adb.py first (e.g., print r) to confirm that the device list is not empty.

**Comment by ylimit** [comment]
I guess it is due to Window encoding issues.
DroidBot uses `split('\n')` to split the command line output. However, Windows separates lines with "\r\n".
Please try the latest commit. 
By the way, maybe we need some tests on Windows. @yzygitzh

**Comment by breezedong** [comment]
Hello,ylimit and yzygitzh, I came to another problem as follow:

`E:\PaperWorkplace\droidbot>droidbot -d 07059e20d0085630 -a dae5b93d99fe9d6d80d647a8a6dbbaf1.apk -env none -event utg_dynamic

INFO:Device:waiting for device
INFO:ADB:adb successfully initiated, the device is 07059e20d0085630
WARNING:Device:Cannot connect to telnet.

Traceback (most recent call last):
  File "D:\Program Files\Python2.7\Scripts\droidbot-script.py", line 9, in <module>
    load_entry_point('droidbot', 'console_scripts', 'droidbot')()
  File "e:\paperworkplace\droidbot\droidbot\droidbot\start.py", line 76, in main
    quiet=opts.quiet)
  File "e:\paperworkplace\droidbot\droidbot\droidbot\droidbot.py", line 49, in __init__
    self.device = Device(device_serial, output_dir=self.output_dir)
  File "e:\paperworkplace\droidbot\droidbot\droidbot\device.py", line 60, in __init__
    self.connect()
  File "e:\paperworkplace\droidbot\droidbot\droidbot\device.py", line 157, in connect
    self.get_view_client()
  File "e:\paperworkplace\droidbot\droidbot\droidbot\device.py", line 217, in get_view_client
    from adapter.viewclient import ViewClient
  File "e:\paperworkplace\droidbot\droidbot\droidbot\adapter\viewclient.py", line 980, in <module>
    from com.dtmilano.android import viewclient
ImportError: No module named com.dtmilano.android`

**Comment by ylimit** [comment]
I removed the import line, please try the lastest commit.
Please start a new issue as it is not related to the current one.
