### ISSUE TITLE
Error when use the -o option and it was not installed with developer option

### ISSUE THREAD

**Issue by joaquingx** [honeynet/droidbot#60]
Hello,

When droidbot is installed without the developer option and tries to use the `-o` action gives the following error:

```
Traceback (most recent call last):
  File "/usr/bin/droidbot", line 11, in <module>
    load_entry_point('droidbot==1.0.2b3', 'console_scripts', 'droidbot')()
  File "build/bdist.linux-x86_64/egg/droidbot/start.py", line 110, in main
  File "build/bdist.linux-x86_64/egg/droidbot/droidbot.py", line 56, in __init__
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1226, in resource_filename
    self, resource_name
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1730, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1751, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'droidbot/resources/index.html'
```
That's because the `resource` directory isn't included in the installation of droidbot. This can be solved using the `data_package` variable. Adding this code to `setup.py` should work:

```python
import os

def package_files(directory):
    paths = []
    for (path, directories, filenames) in os.walk(directory):
        for filename in filenames:
            paths.append(os.path.join("..", path, filename))
    return paths


extra_files = package_files("droidbot/resources/minicap") # neccesary for captures"
style_files = package_files("droidbot/resources/stylesheets")
extra_files.append("../droidbot/resources/index.html")
extra_files += style_files
setup(
                       ...
    package_data={'droidbot': extra_files},
                       ...
)
```

To reproduce, just install droidbot without the `-e` option in `pip` or just use:
`python2 setup.py install`

Cheers,
Joaquin

**Comment by ylimit** [comment]
Thanks for your suggestion.
Should be fixed in the newest commit.

**Comment by joaquingx** [comment]
If you think that my solution is good enough I can open a pull request with that modification

**Comment by ylimit** [comment]
No need. I already committed the fix according to your suggestion. See f6c1f7d48afbdd5e104543cffdfc884ba6aee1e9

**Comment by joaquingx** [comment]
Oh I didn't see, great!
