### ISSUE TITLE
Error on running droidbot

### ISSUE THREAD

**Issue by gnr19911** [honeynet/droidbot#76]
I downloaded latest droidbot. When I run it I get following error 

`WARNING:DroidBot:Something went wrong: 'lxml.etree._Element' object has no attribute 'getElementsByTagName'
Traceback (most recent call last):
  File "/home/gopesh/droidbot/droidbot/droidbot.py", line 87, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "/home/gopesh/droidbot/droidbot/app.py", line 35, in __init__
    self.get_activities()
  File "/home/gopesh/droidbot/droidbot/app.py", line 77, in get_activities
    for activity_dom in manifest.getElementsByTagName("activity"):
AttributeError: 'lxml.etree._Element' object has no attribute 'getElementsByTagName'
[CONNECTION] ADB is disconnected
Error: Unknown id: com.android.inputmethod.latin/.LatinIME
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!`

**Comment by ddlucad96** [comment]
Have you installed the correct version of Androguard? `pip install androguard==3.0.1`

**Comment by gnr19911** [comment]
@ddlucad96 that solved the problem.
