### ISSUE TITLE
Warns 'lxml.etree._Element' object has no attribute 'getElementsByTagName'

### ISSUE THREAD

**Issue by playSGK** [honeynet/droidbot#80]
WARNING:DroidBot:Something went wrong: 'lxml.etree._Element' object has no attribute 'getElementsByTagName'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/droidbot/droidbot.py", line 87, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "build/bdist.linux-x86_64/egg/droidbot/app.py", line 35, in __init__
    self.get_activities()
  File "build/bdist.linux-x86_64/egg/droidbot/app.py", line 77, in get_activities
    for activity_dom in manifest.getElementsByTagName("activity"):
AttributeError: 'lxml.etree._Element' object has no attribute 'getElementsByTagName'
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!

**Comment by SuadMoh** [comment]
I have the same error..Any help??
WARNING:DroidBot:Something went wrong: 'lxml.etree._Element' object has no attribute 'getElementsByTagName'
Traceback (most recent call last):
  File "/root/droidbot/droidbot/droidbot.py", line 87, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "/root/droidbot/droidbot/app.py", line 35, in __init__
    self.get_activities()
  File "/root/droidbot/droidbot/app.py", line 77, in get_activities
    for activity_dom in manifest.getElementsByTagName("activity"):
AttributeError: 'lxml.etree._Element' object has no attribute 'getElementsByTagName'
Error: Unknown id: com.sec.android.inputmethod/.SamsungKeypad
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
[CONNECTION] ADB is disconnected

**Comment by ylimit** [comment]
Duplicate of #76

**Comment by SuadMoh** [comment]
Thanks

**Comment by rajneesh152** [comment]
I am still facing the same issue. I had done all. You can refer below and please recommand what to do next to resolve issue;

WARNING:DroidBot:Something went wrong: 'NoneType' object has no attribute 'getElementsByTagName'
Traceback (most recent call last):
  File "/home/amity/Downloads/droidbot/droidbot/droidbot.py", line 87, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "/home/amity/Downloads/droidbot/droidbot/app.py", line 35, in __init__
    self.get_activities()
  File "/home/amity/Downloads/droidbot/droidbot/app.py", line 77, in get_activities
    for activity_dom in manifest.getElementsByTagName("activity"):
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
[CONNECTION] ADB is disconnected
Error: Unknown id: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
root@amity:/home/amity/Downloads/droidbot/droidbot# pip install androguard==3.0.1
Requirement already satisfied: androguard==3.0.1 in /usr/local/lib/python2.7/dist-packages

**Comment by rajneesh152** [comment]
Please help

**Comment by ylimit** [comment]
Should be fixed in the newest version.

**Comment by SuadMoh** [comment]
Dear developer,
What program  do you use to develop the Droidbot?? Have you used vivy??
Appreciate your support ..

Sent from my iPad

On Jul 6, 2018, at 11:08 AM, Yuanchun Li <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be fixed in the newest version.
