### ISSUE TITLE
error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by DrSahoo** [honeynet/droidbot#81]
We have been getting this error when testing with some apps. Droidbot works fine with most apps, but gives the following error with few apps. Any suggestions on how to fix this error?

RUN APP: com.contextlogic.wish.apk
droidbot -d 024a07b4e14fa992 -a /home/privacyproxy/testbed/apps/top_free_13032018/com.contextlogic.wish.apk -policy dfs_greedy -timeout 150 -count 10000 -grant_perm -keep_env -keep_app -interval 15 -o 024a07b4e14fa992/com.contextlogic.wish.apk -script /home/privacyproxy/PPEval/droidbot_scripts/facebook_loggin.json
WARNING:DroidBot:Something went wrong: unpack requires a string argument of length 4
Traceback (most recent call last):
  File "/home/privacyproxy/droidbot/droidbot/droidbot.py", line 83, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "/home/privacyproxy/droidbot/droidbot/app.py", line 28, in __init__
    self.androguard = AndroguardAnalysis(self.app_path)
  File "/home/privacyproxy/droidbot/droidbot/app.py", line 202, in __init__
    self.a = APK(app_path)
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/apk.py", line 186, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw), mode=mode)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 857, in _RealGetContents
    x._decodeExtra()
  File "/usr/lib/python2.7/zipfile.py", line 388, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!

**Comment by ylimit** [comment]
Hi @DrSahoo can you share the APK file? It seems the file might be broken.

**Comment by ylimit** [comment]
Close due to no response.
