### ISSUE TITLE
WARNING:Device:push_file file does not exist

### ISSUE THREAD

**Issue by Nimishkhurana** [honeynet/droidbot#90]
I followed steps to setup droidbot but when testing any app i get this error:

WARNING:Device:push_file file does not exist: /home/nimish/droidbot/droidbot/resources/minicap/jni/libs/android-27/arm64-v8a/minicap.so
cannot stat '/home/nimish/droidbot/droidbot/resources/minicap/jni/libs/android-27/arm64-v8a/minicap.so': No such file or directory
Traceback (most recent call last):
  File "/home/nimish/droidbot/droidbot/droidbot.py", line 139, in start
    self.device.set_up()
  File "/home/nimish/droidbot/droidbot/device.py", line 143, in set_up
    adapter.set_up()
  File "/home/nimish/droidbot/droidbot/adapter/minicap.py", line 82, in set_up
    remote_dir=self.remote_minicap_path)
  File "/home/nimish/droidbot/droidbot/device.py", line 756, in push_file
    self.adb.run_cmd(["push", local_file, remote_dir])
  File "/home/nimish/droidbot/droidbot/adapter/adb.py", line 64, in run_cmd
    r = subprocess.check_output(args).strip()
  File "/home/nimish/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/nimish/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', '47012d02', 'push', '/home/nimish/droidbot/droidbot/resources/minicap/jni/libs/android-27/arm64-v8a/minicap.so', '/data/local/tmp/minicap-devel']' returned non-zero exit status 1.
[CONNECTION] ADB is disconnected
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
Please wait while uninstalling the app...

**Comment by smaakd** [comment]
As of now , this project only supports emulators up to Android 8.0 (API level 26) , so use an emulator with API level less than 27, that should solve the problem

**Comment by Nimishkhurana** [comment]
Ok trying on API less than 27 solved the problem, but it would be nice to have support for Android > 8.0
Maybe a issue can be opened for that.

**Comment by yzygitzh** [comment]
This PR #89 should fix the problem.
