### ISSUE TITLE
droidbot stuck at "Please wait while installing the app..."

### ISSUE THREAD

**Issue by harsh7809** [honeynet/droidbot#91]
Following exception occurred in terminal
<img width="675" alt="screenshot 3" src="https://user-images.githubusercontent.com/30545703/52797269-8c18a400-309b-11e9-9e2b-ef7e000c1d2c.png">
  

Exception in thread Thread-7:
Traceback (most recent call last):
  File "c:\users\shiva\appdata\local\programs\python\python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "c:\users\shiva\appdata\local\programs\python\python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\shiva\desktop\major\droidbot-master\droidbot-master\droidbot\adapter\logcat.py", line 61, in handle_output
    f.write(line)
  File "c:\users\shiva\appdata\local\programs\python\python35\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uff0c' in position 63: character maps to <undefined>

**Comment by smaakd** [comment]
did you try installing the app in the emulator before running droidbot ? If not then try that.
