### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tear_down'

### ISSUE THREAD

**Issue by Sai-Adarsh** [honeynet/droidbot#92]
* I tried starting droidbot
```sh
droidbot -a <path_to_apk> -o output_dir
```
* I'm getting this error.

```sh
Traceback (most recent call last):
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\droidbot.py", line 95, in __init__
    ignore_ad=ignore_ad)
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\device.py", line 41, in __init__
    all_devices = get_available_devices()
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\utils.py", line 39, in get_available_devices
    r = subprocess.check_output(["adb", "devices"])
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\droidbot.py", line 95, in __init__
    ignore_ad=ignore_ad)
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\device.py", line 41, in __init__
    all_devices = get_available_devices()
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\utils.py", line 39, in get_available_devices
    r = subprocess.check_output(["adb", "devices"])
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\saiadarsh\anaconda3\Lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saiadarsh\Desktop\GSoC\droidbot\venv\Scripts\droidbot-script.py", line 11, in <module>
    load_entry_point('droidbot', 'console_scripts', 'droidbot')()
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\start.py", line 168, in main
    replay_output=opts.replay_output)
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\droidbot.py", line 116, in __init__
    self.stop()
  File "c:\users\saiadarsh\desktop\gsoc\droidbot\droidbot\droidbot.py", line 188, in stop
    self.device.tear_down()
AttributeError: 'NoneType' object has no attribute 'tear_down'
```

**Comment by ylimit** [comment]
Looks like you don't have `adb` in your PATH.
