### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'policy'

### ISSUE THREAD

**Issue by Rain0193** [honeynet/droidbot#98]
when I use -script start:
{
    "views": {
        "login_phone": {
            "resource_id": "com.taihe.jokerxue:id/et_phone_num",
            "class": "android.widget.EditText"
        },
        "get_verification": {
            "resource_id": "com.taihe.jokerxue:id/tv_get_verification",
            "class": "android.widget.TextView"
        },
		"send_verification": {
			"resource_id": "com.taihe.jokerxue:id/et_verification",
			"class": "android.widget.EditText"
		},
        "login_button": {
            "resource_id": "com.taihe.jokerxue:id/btn_enter",
            "class": "android.widget.Button"
        }
    },
    "states": {
        "login_state": {
            "views": ["login_phone", "get_verification", "send_verification", "login_button"]
        }
    },
    "operations": {
        "login_operation": [
            {
                "event_type": "set_text",
                "target_view": "login_phone",
                "text": "12608001103"
            },
            {
                "event_type": "touch",
                "target_view": "get_verification"
            },
			{
				"event_type": "set_text",
				"target_view": "send_verification",
				"text": "1234"
			},
            {
                "event_type": "touch",
                "target_view": "login_button"
            },
            {
                "event_type": "exit"
            }
        ]
    },
    "main": {
        "login_state": ["login_operation"]
    }
}
ScriptSyntaxError: ViewSelector.class: type should be <type 'str'>, <type 'unicode'> given
[CONNECTION] ADB is disconnected
[CONNECTION] DroidBotIme is disconnected
Traceback (most recent call last):
  File "/usr/local/bin/droidbot", line 11, in <module>
    load_entry_point('droidbot', 'console_scripts', 'droidbot')()
  File "/Users/taiheminione/Public/droidbot/droidbot/start.py", line 168, in main
    replay_output=opts.replay_output)
  File "/Users/taiheminione/Public/droidbot/droidbot/droidbot.py", line 116, in __init__
    self.stop()
  File "/Users/taiheminione/Public/droidbot/droidbot/droidbot.py", line 191, in stop
    if hasattr(self.input_manager.policy, "master") and \
AttributeError: 'NoneType' object has no attribute 'policy'

**Comment by ylimit** [comment]
Looks like a typical encoding error. Will take a look soon.

**Comment by yzygitzh** [comment]
Hi @Rain0193 , please share your APK and script file with us.

**Comment by Rain0193** [comment]
Hi @yzygitzh ：
{
    "views": {
        "login_phone": {
            "resource_id": "com.taihe.jokerxue:id/et_phone_num",
            "class": "android.widget.EditText"
        },
        "get_verification": {
            "resource_id": "com.taihe.jokerxue:id/tv_get_verification",
            "class": "android.widget.TextView"
        },
		"send_verification": {
			"resource_id": "com.taihe.jokerxue:id/et_verification",
			"class": "android.widget.EditText"
		},
        "login_button": {
            "resource_id": "com.taihe.jokerxue:id/btn_enter",
            "class": "android.widget.Button"
        }
    },
    "states": {
        "login_state": {
            "views": ["login_phone", "get_verification", "send_verification", "login_button"]
        }
    },
    "operations": {
        "login_operation": [
            {
                "event_type": "set_text",
                "target_view": "login_phone",
                "text": "12608001103"
            },
            {
                "event_type": "touch",
                "target_view": "get_verification"
            },
			{
				"event_type": "set_text",
				"target_view": "send_verification",
				"text": "1234"
			},
            {
                "event_type": "touch",
                "target_view": "login_button"
            },
            {
                "event_type": "exit"
            }
        ]
    },
    "main": {
        "login_state": ["login_operation"]
    }
}

**Comment by Rain0193** [comment]
@yzygitzh 
```json
{
    "views": {
        "login_phone": {
            "resource_id": "com.taihe.jokerxue:id/et_phone_num",
            "class": "android.widget.EditText"
        },
        "get_verification": {
            "resource_id": "com.taihe.jokerxue:id/tv_get_verification",
            "class": "android.widget.TextView"
        },
		"send_verification": {
			"resource_id": "com.taihe.jokerxue:id/et_verification",
			"class": "android.widget.EditText"
		},
        "login_button": {
            "resource_id": "com.taihe.jokerxue:id/btn_enter",
            "class": "android.widget.Button"
        }
    },
    "states": {
        "login_state": {
            "views": ["login_phone", "get_verification", "send_verification", "login_button"]
        }
    },
    "operations": {
        "login_operation": [
            {
                "event_type": "set_text",
                "target_view": "login_phone",
                "text": "12608001103"
            },
            {
                "event_type": "touch",
                "target_view": "get_verification"
            },
			{
				"event_type": "set_text",
				"target_view": "send_verification",
				"text": "1234"
			},
            {
                "event_type": "touch",
                "target_view": "login_button"
            },
            {
                "event_type": "exit"
            }
        ]
    },
    "main": {
        "login_state": ["login_operation"]
    }
}
```

**Comment by Rain0193** [comment]
> Hi @Rain0193 , please share your origin script file with us.

```json```

{
    "views": {
        "login_phone": {
            "resource_id": "com.taihe.jokerxue:id/et_phone_num",
            "class": "android.widget.EditText"
        },
        "get_verification": {
            "resource_id": "com.taihe.jokerxue:id/tv_get_verification",
            "class": "android.widget.TextView"
        },
		"send_verification": {
			"resource_id": "com.taihe.jokerxue:id/et_verification",
			"class": "android.widget.EditText"
		},
        "login_button": {
            "resource_id": "com.taihe.jokerxue:id/btn_enter",
            "class": "android.widget.Button"
        }
    },
    "states": {
        "login_state": {
            "views": ["login_phone", "get_verification", "send_verification", "login_button"]
        }
    },
    "operations": {
        "login_operation": [
            {
                "event_type": "set_text",
                "target_view": "login_phone",
                "text": "12608001103"
            },
            {
                "event_type": "touch",
                "target_view": "get_verification"
            },
			{
				"event_type": "set_text",
				"target_view": "send_verification",
				"text": "1234"
			},
            {
                "event_type": "touch",
                "target_view": "login_button"
            },
            {
                "event_type": "exit"
            }
        ]
    },
    "main": {
        "login_state": ["login_operation"]
    }
}

**Comment by Rain0193** [comment]
> Hi @Rain0193 , please share your origin script file with us.

```json
{
    "views": {
        "login_phone": {
            "resource_id": "com.taihe.jokerxue:id/et_phone_num",
            "class": "android.widget.EditText"
        },
        "get_verification": {
            "resource_id": "com.taihe.jokerxue:id/tv_get_verification",
            "class": "android.widget.TextView"
        },
		"send_verification": {
			"resource_id": "com.taihe.jokerxue:id/et_verification",
			"class": "android.widget.EditText"
		},
        "login_button": {
            "resource_id": "com.taihe.jokerxue:id/btn_enter",
            "class": "android.widget.Button"
        }
    },
    "states": {
        "login_state": {
            "views": ["login_phone", "get_verification", "send_verification", "login_button"]
        }
    },
    "operations": {
        "login_operation": [
            {
                "event_type": "set_text",
                "target_view": "login_phone",
                "text": "12608001103"
            },
            {
                "event_type": "touch",
                "target_view": "get_verification"
            },
			{
				"event_type": "set_text",
				"target_view": "send_verification",
				"text": "1234"
			},
            {
                "event_type": "touch",
                "target_view": "login_button"
            },
            {
                "event_type": "exit"
            }
        ]
    },
    "main": {
        "login_state": ["login_operation"]
    }
}

```

**Comment by sujon335** [comment]
Having similar issue with the following script : 
{
    "views": {
        "sign_up_button":{
            "resource_id": "com.punchh.fazolis:id/HomeScreen_B_SignUp",
            "class": "android.widget.Button"
        }
        
    },
    "states": {
        "home_state": {
            "activity": "com.punchh.fazolis.CustomHomeActivity",
            "views": ["sign_up_button"]
        }
    },
    "operations": {
        "home_operation": [
            {
                "event_type": "touch",
                "target_view": "sign_up_button"
            }
        ]
    },
    "main": {
        "home_state": ["home_operation"]
    }
}
